# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    volumes:
      - ./search-index-directory:/usr/share/elasticsearch/data
    ports:
      - 9865:9200
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9865/_cluster/health?wait_for_status=green&timeout=10s']
      interval: 5s
      timeout: 10s
      retries: 10
